### ISSUE TITLE
rclone启动不起来

### ISSUE THREAD

**Issue by murazi** [quanjindeng/Actions_OpenWrt-Amlogic#3]
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute cbi dispatcher target for entry '/admin/nas/rclone'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/rclone.lua:30: attempt to concatenate local 'trip' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>

请帮忙看看?

**Comment by quanjindeng** [comment]
没有用过rclone，不了解

**Comment by murazi** [comment]
5.4.176-flippy-69+o

这个版本下的,rclone启用保存就报错了,没有做其它设置
