### ISSUE TITLE
5.4.176-flippy-69+o的N1固件SMB和NFS共享不起作用

### ISSUE THREAD

**Issue by murazi** [quanjindeng/Actions_OpenWrt-Amlogic#4]
本地挂载正常，但SMB和NFS设置共享目录均不可用

安卓通过VLC和NPlayer测试
NFS可以访问到共享的目录，但目录下的文件看不到
SMB共享的目录均看不到

WIN10下开启NFS和SMB服务
映射硬盘均提示意外错误，无法映射

**Comment by quanjindeng** [comment]
权限问题，NFS直接共享OpenWrt根目录你就会发现部分文件夹有内容、部分显示为空。smb也一样，创建root用户验证后即可。

**Comment by quanjindeng** [comment]
避免其他人也有这个问题，补充一下恩山类似问题的帖子[https://www.right.com.cn/forum/thread-4583992-1-1.html](url)
善用搜索，以后插件具体问题的issue不再回复。

**Comment by murazi** [comment]
恩山搜nfs共享问题只有4个，且都没有明确的解决方法
百度也搜了好多，确实没有准确的答案才来问的

对linux也不熟悉
请问创建root用户验证是什么?(特意搜索了资料，大部分是如何创建root用户,好像和你说的不是一回事)

看了你发的连接，也将共享参数改为了（rw,sync,root_squash,all_squash,insecure,no_subtree_check）
依然显示不出来文件夹内容，因为家里主路由也是OP用了很多年，SMB共享是没有问题的，所以确实没接触到过这种情况

还望理解

**Comment by quanjindeng** [comment]
> smbpasswd -a root
为smb添加root用户

仔细看帖子，NFS的问题在于需要把目录设置到需要访问但你现在无法显示的目录。比如我设置为/mnt这个目录，访问这目录下的mmcblk2p4文件夹显示为空，修改目录为/mnt/mmcblk2p4就正常了
